### ISSUE TITLE
Scanner can't connect to mailservers for comcast.net

### ISSUE THREAD

**Issue by jgillula** [EFForg/starttls-scanner#83]
https://starttls-everywhere.org/results/?comcast.net says "Could not connect to comcast.net We couldn't connect to any of your mailservers!"

But when I run the checker locally (`./starttls-check -domain comcast.net`) I'm able to connect to at least mx1.comcast.net (but not mx2.comcast.net)

**Comment by sydneyli** [comment]
Looks like this is because we don't have reverse DNS set up for `starttls-everywhere.org`. Opened an internal ticket!

**Comment by sydneyli** [comment]
Just kidding, we've been blacklisted: http://postmaster.comcast.net/smtp-error-codes.php#BL000010

**Comment by wgreenberg** [comment]
Cloudmark has reset our IP reputation, should be good to go now

**Comment by jgillula** [comment]
Looks fixed to me! 
![screenshot from 2018-07-16 11 40 31](https://user-images.githubusercontent.com/6627267/42776822-16f2e182-88ed-11e8-92c2-12ef4f6003d8.png)
